[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x", "curl"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "npm start"

[variables]
PORT = "8080"

[healthcheck]
interval = "30s"
timeout = "10s"
retries = 3
start_period = "40s" 